### ISSUE TITLE
Unable to view any competitions before 2023

### ISSUE THREAD

**Issue by karl-johnson** [avgupta456/statbotics#262]
Attempting to visit any competition page outside of the 2023 season competitions gives an error page for me:

`Application error: a client-side exception has occurred (see the browser console for more information).`

In the browser console:

```
instrument.js?e1d9:108 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at tabs.tsx:40:24
    at Array.findIndex (<anonymous>)
    at u (tabs.tsx:39:25)
    at rp (react-dom.production.min.js?2c9e:110:141)
    at lZ (react-dom.production.min.js?2c9e:269:336)
    at oF (react-dom.production.min.js?2c9e:255:349)
    at react-dom.production.min.js?2c9e:253:459
    at oz (react-dom.production.min.js?2c9e:253:459)
    at oR (react-dom.production.min.js?2c9e:247:249)
    at ox (react-dom.production.min.js?2c9e:245:264)
    at I (index.js?4b73:19:2832)
    at b.port1.onmessage (index.js?4b73:19:1555)
```
Reproducible in Chrome, Edge, and Firefox. In Firefox, however, the error in the console is different:
```
TypeError: e.title is undefined
    x tabs.tsx:40
    i tabs.tsx:39
    rp react-dom.production.min.js:110
    lZ react-dom.production.min.js:269
    oF react-dom.production.min.js:255
    oz react-dom.production.min.js:253
    oz react-dom.production.min.js:253
    oR react-dom.production.min.js:247
    ox react-dom.production.min.js:245
    I index.js:19
    onmessage index.js:19
    488 index.js:19
    r index.js:19
    833 index.js:19
    r index.js:19
    26183 index.js:19
    26183 index.js:19
    Webpack 22
```

**Comment by avgupta456** [comment]
Thanks for the bug report, I think I accidently introduced it when deploying the EPA Breakdowns. It should be fixed now!
